---
Gemfile:
  required:
    ':development':
      - gem: puppet-blacksmith
        version: '~> 3.4'
      - gem: puppet-strings

Rakefile:
  requires:
    - puppet_blacksmith/rake_tasks
    - puppet-lint/tasks/puppet-lint

.gitignore:
  required:
    - /update_report.txt
